attention_terminal:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_DATABASE', 'default') }}"
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8443') | as_number }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', '') }}"
      secure: "{{ env_var('CLICKHOUSE_SECURE', 'True') | as_bool }}"
      verify: "{{ env_var('CLICKHOUSE_VERIFY', 'True') | as_bool }}"
      connect_timeout: 10
      send_receive_timeout: 300
