-- +goose Up

-- ============================================================
-- Real-time Events API poller + deterministic timelapse infrastructure.
--
-- 1. default.events_api_etags — per-repo ETag cache for the GitHub Events
--    API. A 304 Not Modified response costs zero rate-limit quota, so the
--    60s poller only spends quota when a repo actually produced events.
-- 2. curated.repo_timelapse — deterministic per-repo per-hour commentary,
--    generated by the generate-timelapse task from event patterns (no LLM).
--    ReplacingMergeTree(generated_at) lets the hourly task regenerate a
--    window as late-arriving GH Archive rows fill it in.
-- 3. Watchlist prune — remove auto-seeded repos with zero engagement in the
--    firehose over the last 7 days. The auto-seed picked up ~89 push-only CI
--    bots (tens of thousands of pushes, zero stars/forks/PRs/issues) and ~11
--    repos that have gone silent; they would waste poll quota and produce
--    empty timelapses. ~94 engaged repos remain. Manually added rows are
--    kept.
-- ============================================================

CREATE TABLE IF NOT EXISTS default.events_api_etags
(
    repo_name  String,
    etag       String,
    updated_at DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY repo_name;

CREATE TABLE IF NOT EXISTS curated.repo_timelapse
(
    repo_name     String,
    window_start  DateTime,
    window_end    DateTime,
    commentary    String,
    themes        Array(String),
    event_count   UInt32,
    key_events    Array(String),
    generated_at  DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(generated_at)
ORDER BY (repo_name, window_start)
TTL window_start + INTERVAL 90 DAY;

-- Prune dead auto-seed rows. Engagement = any non-push event in the firehose
-- in the last 7 days (pushes alone do not count — that is the CI-bot
-- signature). Measured against default.github_events_stream (swapped in by
-- migration 21), NOT gh_repo_daily: the old pipeline's coverage has degraded
-- (golang/go shows 11 pushes/week there vs 61 + PRs + reviews in the
-- firehose), and it undercounts engagement severely enough to prune active
-- repos by mistake. 7 days matches the stream's current backfill depth.
ALTER TABLE watchlist DELETE
WHERE source = 'auto-seed'
  AND repo_name NOT IN (
      SELECT DISTINCT repo_name
      FROM default.github_events_stream
      WHERE created_at >= now() - INTERVAL 7 DAY
        AND event_type != 'PushEvent'
  )
SETTINGS mutations_sync = 1;

-- +goose Down
DROP TABLE IF EXISTS curated.repo_timelapse;
DROP TABLE IF EXISTS default.events_api_etags;
-- Pruned watchlist rows are not restored; the refresh-repo-activity auto-seed
-- re-adds any repo that regains engagement on its next run.
